# Generated by Django 6.0.5 on 2026-05-16 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'دسته هزینه', 'verbose_name_plural': 'دسته\u200cبندی هزینه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='expensedetail',
            options={'verbose_name': 'جزئیات هزینه', 'verbose_name_plural': 'جزئیات هزینه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'verbose_name': 'تراکنش مالی', 'verbose_name_plural': 'تراکنش\u200cهای مالی'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'صندوق', 'verbose_name_plural': 'صندوق\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name': 'دسته درآمد', 'verbose_name_plural': 'دسته\u200cبندی درآمدها'},
        ),
        migrations.AlterModelOptions(
            name='incomedetail',
            options={'verbose_name': 'جزئیات درآمد', 'verbose_name_plural': 'جزئیات درآمد'},
        ),
        migrations.AlterModelOptions(
            name='transferdetail',
            options={'verbose_name': 'جزئیات انتقال', 'verbose_name_plural': 'جزئیات انتقال\u200cها'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام مناسبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مناسبت',
                'verbose_name_plural': 'مناسبت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_finance.event'),
            preserve_default=False,
        ),
    ]
