# Generated by Django 6.0.5 on 2026-05-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0003_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='image_receipt',
            field=models.ImageField(default=1, upload_to='images/receipts'),
            preserve_default=False,
        ),
    ]
