# Generated by Django 6.0.5 on 2026-05-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'verbose_name': 'دسته انبار', 'verbose_name_plural': 'دسته\u200cبندی انبار'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'کالای انبار', 'verbose_name_plural': 'کالاهای انبار'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'verbose_name': 'تراکنش انبار', 'verbose_name_plural': 'تراکنش\u200cهای انبار'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'تامین کننده', 'verbose_name_plural': 'تامین کنندگان'},
        ),
    ]
