# Generated by Django 6.0.5 on 2026-05-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_alter_inventorycategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycategory',
            name='parent',
        ),
    ]
